// apps/english-web/app/(main)/vocab/page.tsx
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import VocabPicture from '@/components/VocabPicture';

import type { VocabWord, VocabListResponse } from '@/lib/types';

const LEVELS = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'] as const;

async function fetchVocab(level?: string, page = 1) {
  const params = new URLSearchParams({ page: String(page), limit: '30' });
  if (level) params.set('level', level);
  const res = await fetch(`/api/vocab?${params}`);
  return res.json() as Promise<VocabListResponse>;
}

function VocabCard({ w }: { w: VocabWord }) {
  const [flipped, setFlipped] = useState(false);

  return (
    <div
      className="card vocab-list-card"
      style={{ cursor: 'pointer', userSelect: 'none' }}
      onClick={() => setFlipped((f) => !f)}
    >
      <div className="vocab-list-card-inner">
        <VocabPicture
          word={w.word}
          meaning={w.meaningVi}
          imageUrl={w.imageUrl}
          size="sm"
          className="vocab-list-card-picture"
          alt={w.word}
        />
        <div className="vocab-list-card-body">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.5rem' }}>
            <span className={`badge badge-${w.level}`}>{w.level}</span>
            {w.partOfSpeech && (
              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{w.partOfSpeech}</span>
            )}
          </div>
          <div style={{ fontSize: '1.25rem', fontWeight: 700 }}>{w.word}</div>
          {w.phonetic && (
            <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '0.25rem' }}>{w.phonetic}</div>
          )}
          {flipped ? (
            <>
              <div style={{ color: 'var(--accent)', fontWeight: 600, marginTop: '0.5rem' }}>{w.meaningVi}</div>
              {w.exampleEn && (
                <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginTop: '0.4rem', fontStyle: 'italic' }}>
                  &ldquo;{w.exampleEn}&rdquo;
                </div>
              )}
              {w.exampleVi && (
                <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '0.2rem' }}>→ {w.exampleVi}</div>
              )}
            </>
          ) : (
            <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '0.5rem' }}>Nhấn để xem nghĩa</div>
          )}
          {w.topic && (
            <div style={{ marginTop: '0.5rem', fontSize: '0.75rem', color: 'var(--text-muted)' }}>
              #{w.topic.name}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default function VocabPage() {
  const [level, setLevel] = useState<string>('');
  const [page, setPage] = useState(1);

  const { data, isLoading } = useQuery({
    queryKey: ['vocab', level, page],
    queryFn: () => fetchVocab(level || undefined, page),
  });

  const totalPages = data ? Math.ceil(data.total / data.limit) : 1;

  return (
    <div className="container" style={{ padding: '1.5rem 1rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem', flexWrap: 'wrap', gap: '0.75rem' }}>
        <div>
          <h1 style={{ marginBottom: '0.15rem' }}>Từ vựng</h1>
          {data && <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>{data.total} từ • nhấn thẻ để xem nghĩa</p>}
        </div>
        <Link href="/vocab/flashcard" className="btn">Flashcard</Link>
        <Link href="/vocab/picture" className="btn">Từ điển tranh</Link>
        <Link href="/vocab/review" className="btn btn-primary">SRS Review →</Link>
      </div>

      <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1.25rem', flexWrap: 'wrap' }}>
        <button className={`btn${!level ? ' btn-primary' : ''}`} onClick={() => { setLevel(''); setPage(1); }}>Tất cả</button>
        {LEVELS.map((l) => (
          <button key={l} className={`btn${level === l ? ' btn-primary' : ''}`} onClick={() => { setLevel(l); setPage(1); }}>
            {l}
          </button>
        ))}
      </div>

      {isLoading ? (
        <p style={{ color: 'var(--text-muted)' }}>Đang tải...</p>
      ) : data?.words?.length === 0 ? (
        <div className="card" style={{ textAlign: 'center', padding: '3rem', color: 'var(--text-muted)' }}>
          Chưa có từ vựng nào. Thêm data qua seeder hoặc Admin.
        </div>
      ) : (
        <div style={{ display: 'grid', gap: '0.75rem', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))' }}>
          {data?.words?.map((w) => <VocabCard key={w.id} w={w} />)}
        </div>
      )}

      {totalPages > 1 && (
        <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center', marginTop: '1.5rem' }}>
          <button className="btn" disabled={page === 1} onClick={() => setPage((p) => p - 1)}>← Trước</button>
          <span style={{ padding: '0.5rem 1rem', color: 'var(--text-muted)', fontSize: '0.9rem' }}>{page} / {totalPages}</span>
          <button className="btn" disabled={page === totalPages} onClick={() => setPage((p) => p + 1)}>Sau →</button>
        </div>
      )}
    </div>
  );
}

// frontend/src/app/pages/vocab.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ApiService } from '../core/api.service';
import { LEVELS, VocabPage } from '../core/models';

@Component({
  selector: 'app-vocab',
  imports: [RouterLink],
  template: `
    <div class="container page">
      <div class="row" style="justify-content: space-between; margin-bottom: 1rem;">
        <div>
          <h1>Từ vựng</h1>
          <p class="muted">{{ data()?.total ?? 0 }} từ · nhấn thẻ để xem nghĩa</p>
        </div>
        <div class="row">
          <a class="btn" routerLink="/vocab/flashcard">Flashcard</a>
          <a class="btn" routerLink="/vocab/picture">Từ điển tranh</a>
          <a class="btn btn-primary" routerLink="/vocab/review">SRS Review</a>
        </div>
      </div>
      <div class="row" style="margin-bottom: 1rem;">
        <button class="btn" [class.btn-primary]="level() === ''" (click)="setLevel('')">Tất cả</button>
        @for (item of levels; track item) {
          <button class="btn" [class.btn-primary]="level() === item" (click)="setLevel(item)">{{ item }}</button>
        }
      </div>
      @if (loading()) { <p class="muted">Đang tải...</p> }
      <div class="grid">
        @for (word of data()?.words ?? []; track word.id) {
          <button class="card" style="text-align: left; cursor: pointer;" (click)="flip(word.id)">
            <div class="row" style="justify-content: space-between;">
              <span class="badge" [class]="'badge badge-' + word.level">{{ word.level }}</span>
              <span class="muted" style="font-size: 0.75rem;">{{ word.partOfSpeech }}</span>
            </div>
            <div style="font-size: 1.25rem; font-weight: 700;">{{ word.word }}</div>
            <div class="muted">{{ word.phonetic }}</div>
            @if (open() === word.id) {
              <div style="color: var(--accent); font-weight: 600; margin-top: 0.4rem;">{{ word.meaningVi }}</div>
              @if (word.exampleEn) { <div class="muted" style="font-style: italic;">"{{ word.exampleEn }}"</div> }
              @if (word.exampleVi) { <div class="muted">→ {{ word.exampleVi }}</div> }
            } @else {
              <div class="muted" style="margin-top: 0.4rem;">Nhấn để xem nghĩa</div>
            }
            @if (word.topic) { <div class="muted" style="margin-top: 0.4rem;">#{{ word.topic.name }}</div> }
          </button>
        }
      </div>
      @if ((data()?.total ?? 0) > (data()?.limit ?? 30)) {
        <div class="row" style="justify-content: center; margin-top: 1rem;">
          <button class="btn" [disabled]="page() === 1" (click)="changePage(-1)">Trước</button>
          <span class="muted">Trang {{ page() }}</span>
          <button class="btn" (click)="changePage(1)">Sau</button>
        </div>
      }
    </div>
  `,
})
export class VocabComponent implements OnInit {
  private api = inject(ApiService);
  levels = LEVELS;
  level = signal('');
  page = signal(1);
  data = signal<VocabPage | null>(null);
  loading = signal(true);
  open = signal<number | null>(null);

  ngOnInit() { this.load(); }

  setLevel(level: string) {
    this.level.set(level);
    this.page.set(1);
    this.load();
  }

  changePage(delta: number) {
    this.page.update((p) => Math.max(1, p + delta));
    this.load();
  }

  flip(id: number) {
    this.open.set(this.open() === id ? null : id);
  }

  private load() {
    this.loading.set(true);
    this.api.vocab(this.level(), this.page()).subscribe({
      next: (data) => { this.data.set(data); this.loading.set(false); },
      error: () => this.loading.set(false),
    });
  }
}
